application:
  postgres:
    datasource:
      url: jdbc:postgresql://localhost:5432/demodb
      username: demo
      password:
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
        jdbc:
          lob:
            non_contextual_creation: true
          dialect: org.hibernate.dialect.ProgressDialect
