spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demodb
    username: demo
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /api
  error:
    include-message: always

build:
  version: @project.version@

logging:
  level:
    it.laterale.cloud: DEBUG

security:
  secret: chiavesupersegretissima
  prefix: 'Bearer '
  param: Authorization

admin:
  email: admin@test.com
  password: test

springdoc:
  packages-to-scan: it.laterale.cloud.controllers
  api-docs:
    path: /public/v3/api-docs
  swagger-ui:
    path: /public/swagger